params:
  epochs: 30
  batch_size: 32
  no_classes: 10
  loss_function: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: SGD
  validation_datasize: 5000
  


artifacts:
  artifacts_dir: artifacts
  model_dr: model
  plots_dir: plots
  checkpoints_dor: checkpoints

logs:
  log_dir: log_dir
  general_log: general_logs
  tensorboard_logs: tensorboard_logs